import { NumeralCatagory, NumeralStructure, NumeralValue, RusNumeralInterface } from "./types";

export const rusNumerals: RusNumeralInterface[] = [
  {
    stem: 'нол',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '0',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs6',
  },
  {
    stem: 'один',
    stem1: 'одн',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs',
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '2',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs1',
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '3',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs2',
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '4',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs3',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '5',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '6',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '7',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '8',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs5',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '9',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '10',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'одиннадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '11',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'двенадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '12',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'тринадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '13',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'четырнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '14',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'пятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '15',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'шестнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '16',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'семнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '17',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'восемнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '18',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'девятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '19',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'двадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '20',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'тридцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '30',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'сорок',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '40',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs7',
  },
  {
    stem: 'девяност',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '90',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs8',
  },
  {
    stem: 'ст',
    stem1: 'сот',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '100',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs8',
  },
  {
    stem: 'тысяч',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs9',
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '*0',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqc',
  },
  {
    stem: 'сот',
    stem1: 'ст',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '*00',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqc1',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '50',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '60',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '70',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '80',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs5',
    declensionZ1: 'pqc',
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '400',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs3',
    declensionZ1: 'pqc3',
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '300',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs2',
    declensionZ1: 'pqc3',
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '200',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqc4',
    declensionZ1: 'pqc2',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '500',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '600',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '700',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '800',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs5',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '900',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'миллион',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000000',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs10',
  },
  {
    stem: 'миллиард',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000000000',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs10',
  },
  {
    stem: 'перв',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'втор',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '2',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'трет',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '3',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '6*a',
  },
  {
    stem: 'четвёрт',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '4',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '5',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '6',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'седьм',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '7',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'восьм',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '8',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '9',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '10',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'одиннадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '11',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'двенадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '12',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'тринадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '13',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'четырнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '14',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'пятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '15',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'шестнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '16',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'семнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '17',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'восемнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '18',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'девятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '19',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'двадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '20',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'тридцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '30',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'сороков',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '40',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'девяност',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '90',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '50',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '60',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '70',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'десят',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '80',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs5',
    declensionZ1: '1a',
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '400',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs3',
    declensionZ1: '1a',
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '300',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs2',
    declensionZ1: '1a',
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '200',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqc4',
    declensionZ1: '1a',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '500',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '600',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '700',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '800',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs5',
    declensionZ1: '1a',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '900',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'сот',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '100',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'тысячн',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'миллионнн',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000000',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'миллиардн',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000000000',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  }

  ,
  {
    stem: 'перв',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'втор',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '2',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'трет',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '3',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '6*a',
  }
  ,
  {
    stem: 'четвёрт',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '4',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '5',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '6',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'седьм',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '7',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'восьм',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '8',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '9',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '10',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'одиннадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '11',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'двенадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '12',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'тринадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '13',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'четырнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '14',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'пятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '15',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'шестнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '16',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'семнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '17',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'восемнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '18',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'девятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '19',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'двадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '20',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'тридцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '30',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'сороков',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '40',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1b',
  },
  {
    stem: 'девяност',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '90',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '50',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '60',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '70',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'десят',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '80',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs5',
    declensionZ1: '1a',
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '400',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs3',
    declensionZ1: '1a',
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '300',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs2',
    declensionZ1: '1a',
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '200',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqc4',
    declensionZ1: '1a',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '500',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '600',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '700',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '800',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs5',
    declensionZ1: '1a',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: true,
    digitalWrite: '900',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    declensionZ: 'pqs4',
    declensionZ1: '1a',
  },
  {
    stem: 'сот',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '100',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'тысячн',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'миллионнн',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000000',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  },
  {
    stem: 'миллиардн',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000000000',
    numeralValue: NumeralValue.Orinal,
    structure: NumeralStructure.Simple,
    declensionZ: '1a',
  }


];