import { RusGender, NumeralCatagory, NumeralStructure, NumeralValue, RusNumeralInterface } from "./types";

export const rusNumerals: RusNumeralInterface[] = [
  {
    stem: 'нол',
    stem1: '',
    stem2: '',
    possiblePlural: true,
    digitalWrite: '0',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs6',
  },
  {
    stem: 'один',
    stem1: 'одн',
    stem2: '',
    possiblePlural: true,
    digitalWrite: '1',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs',
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '2',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs1',
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '3',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs2',
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '4',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs3',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '5',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '6',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '7',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '8',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs5',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '9',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    possiblePlural: false,
    digitalWrite: '10',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  }
];