import { RusNumeralInterface, NumeralType, NumeralStructure, NumeralRank, RusGender } from "./types";

export const rusNumerals: RusNumeralInterface[] = [
  {
    stem: 'нол',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 0,
    declension: 'pqs0',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'один',
    stem1: 'одн',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    gender: RusGender.Masc,
    value: 1,
    declension: 'pqs1',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'один',
    stem1: 'одн',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    gender: RusGender.Femn,
    value: 1,
    declension: 'pqs1',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'один',
    stem1: 'одн',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    gender: RusGender.Neut,
    value: 1,
    declension: 'pqs1',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    gender: RusGender.Masc,
    value: 2,
    declension: 'pqs2',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    gender: RusGender.Femn,
    value: 2,
    declension: 'pqs2',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    gender: RusGender.Neut,
    value: 2,
    declension: 'pqs2',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 3,
    declension: 'pqs3',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 4,
    declension: 'pqs4',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 5,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 6,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 7,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 8,
    declension: 'pqs8',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 9,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 10,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },

  {
    stem: 'одиннадцат',
    stem1: '',
    stem2: '',
    value: 11,
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'двенадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 12,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'тринадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 13,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'четырнадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 14,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'пятнадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 15,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'шестнадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 16,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'семнадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 17,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'восемнадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 18,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'девятнадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 19,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'двадцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 20,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'тридцат',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 30,
    declension: 'pqs5-7,9-20,30',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'сорок',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 40,
    declension: 'pqs40',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'пятьдесят',
    stem1: 'пятидесят',
    stem2: 'пятьюдесят',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Complex,
    value: 50,
    declension: 'pqc50,60,70,80',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'шестьдесят',
    stem1: 'шестидесят',
    stem2: 'шестьюдесят',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Complex,
    value: 60,
    declension: 'pqc50,60,70,80',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'семьдесят',
    stem1: 'семидесят',
    stem2: 'семьюдесят',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Complex,
    value: 70,
    declension: 'pqc50,60,70,80',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'восемьдесят',
    stem1: 'восьмидесят',
    stem2: 'восьмьюдесят',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Complex,
    value: 80,
    declension: 'pqc50,60,70,80',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'девяност',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 90,
    declension: 'pqs90,100',
    rank: NumeralRank.ProperQuantitative,
  },
  {
    stem: 'ст',
    stem1: '',
    stem2: '',
    type: NumeralType.Cardinal,
    structure: NumeralStructure.Simple,
    value: 100,
    declension: 'pqs90,100',
    rank: NumeralRank.ProperQuantitative,
  },
];