import { RusGender, NumeralCatagory, NumeralStructure, NumeralValue, RusNumeralInterface } from "./types";

export const rusNumerals: RusNumeralInterface[] = [
  {
    stem: 'нол',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '0',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs6',
  },
  {
    stem: 'один',
    stem1: 'одн',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs',
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '2',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs1',
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '3',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs2',
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '4',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs3',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '5',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '6',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '7',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '8',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs5',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '9',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '10',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'одиннадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '11',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'двенадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '12',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'тринадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '13',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'четырнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '14',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'пятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '15',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'шестнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '16',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'семнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '17',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'восемнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '18',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'девятнадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '19',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'двадцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '20',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'тридцат',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '30',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
  },
  {
    stem: 'сорок',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '40',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs7',
  },
  {
    stem: 'девяност',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '90',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs8',
  },
  {
    stem: 'ст',
    stem1: 'сот',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '100',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs8',
  },
  {
    stem: 'тысяч',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: true,
    digitalWrite: '1000',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs9',
  },
  {
    stem: 'десят',
    stem1: '',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '*0',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqc',
  },
  {
    stem: 'сот',
    stem1: 'ст',
    stem2: '',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '*00',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Simple,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqc1',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '50',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '60',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '70',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'десят',
    stem3: '',
    possiblePlural: false,
    digitalWrite: '80',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs5',
    declensionZ1: 'pqc',
  },
  {
    stem: 'четыр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '400',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs3',
    declensionZ1: 'pqc3',
  },
  {
    stem: 'тр',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '300',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs2',
    declensionZ1: 'pqc3',
  },
  {
    stem: 'дв',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '200',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqc4',
    declensionZ1: 'pqc2',
  },
  {
    stem: 'пят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '500',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'шест',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '600',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'сем',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '700',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'восем',
    stem1: 'восьм',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '800',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs5',
    declensionZ1: 'pqc1',
  },
  {
    stem: 'девят',
    stem1: '',
    stem2: 'ст',
    stem3: 'сот',
    possiblePlural: false,
    digitalWrite: '900',
    numeralValue: NumeralValue.Quantitative,
    structure: NumeralStructure.Complex,
    catagory: NumeralCatagory.ProperQuantitative,
    declensionZ: 'pqs4',
    declensionZ1: 'pqc1',
  }
];